name: 'Push to Dockerhub'
description: 'Crea la img de contenedor indicada y la sube a Dockerhub.'

inputs:
  path:
    description: 'Ruta dónde está el Dockerfile.'
    default: '.'
    required: false
  repositorio:
    description: 'Nombre del repositorio.'
    required: true
  version:
    description: 'Versión de la img.'
    required: true
outputs:
  status:
    description: 'Resultado del build.'
    value: ${{ steps.push-docker.outputs.metadata }}

runs:
  using: 'composite'
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      id: push-docker
      with:
        context: ${{ inputs.path }}
        push: true
        tags: ${{ inputs.repositorio }}:${{ inputs.version }}